#!/usr/bin/env node
/* ============================================================
 *  scripts/build-config.js
 *  -------------------------------------------------------------
 *  在 Vercel Build 阶段执行:把环境变量写入 ./config.js,
 *  供前端运行时通过 window.env 读取。
 *
 *  本脚本不依赖任何 npm 包,可在最干净的 Node 环境下运行。
 * ============================================================ */

const fs   = require("fs");
const path = require("path");

const URL  = process.env.SUPABASE_URL      || "";
const KEY  = process.env.SUPABASE_ANON_KEY || "";

if (!URL || !KEY) {
  console.warn(
    "\n⚠ 未检测到 SUPABASE_URL / SUPABASE_ANON_KEY 环境变量。\n" +
    "  生成的 config.js 将为空字符串,前端会进入未配置态。\n" +
    "  请在 Vercel Dashboard → Settings → Environment Variables 配置。\n"
  );
}

const banner = `/* ⚙ Auto-generated by scripts/build-config.js at ${new Date().toISOString()} *\/`;
const body = `window.env = {
  SUPABASE_URL:      ${JSON.stringify(URL)},
  SUPABASE_ANON_KEY: ${JSON.stringify(KEY)},
};`;

const out = path.resolve(process.cwd(), "config.js");
fs.writeFileSync(out, `${banner}\n${body}\n`, "utf8");
console.log(`✓ config.js 已生成 → ${out}`);
