-- ============================================================
--  leads 表 —— 存储用户提交的 CNC 报价请求
--  字段与 index.html 中 payload 一一对应
-- ============================================================

create table if not exists public.leads (
  id              bigint generated by default as identity primary key,
  name            text        not null,
  phone           text        not null,
  length          numeric     not null,
  width           numeric     not null,
  quantity        integer     not null,
  material        text        not null,
  material_factor numeric     not null,
  price           numeric     not null,
  created_at      timestamptz not null default now()
);

-- 开启行级安全 (RLS)。开启后默认拒绝一切访问,必须显式建策略才能放行。
alter table public.leads enable row level security;

-- 允许匿名用户 (前端用的 anon key) 插入新报价;不给 select / update / delete 权限,
-- 这样陌生人无法看到、修改、删除别人的提交。
create policy "anon can insert leads"
  on public.leads
  for insert
  to anon
  with check (true);
